version: '3.8'



services:
  db:
    image: postgres:16
    container_name: train_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  fetcher_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
    command: sh -c "python backend/wait_for_db.py && python -m backend.main"

  web_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
      - fetcher_service
    command: sh -c "python backend/wait_for_db.py && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

volumes:
  pgdata: